cloneConcurrency: 6

enableColors: true

enableGlobalCache: true

enableHyperlinks: true

enableProgressBars: true

enableTelemetry: false

httpRetry: 3

networkConcurrency: 8

nodeLinker: node-modules

patchFolder: .yarn/patches

yarnPath: .yarn/releases/yarn-4.0.0-rc.25.cjs
