name: CI - API

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.husky'
      - 'sanity-cms/**'
      - 'svelte-app/**'

concurrency: 
  group: api
  cancel-in-progress: true

jobs:
  lint:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: (cd ./express-api && yarn install 2> >(grep -v warning 1>&2))
      
      - name: Run eslint
        run: (cd ./express-api && yarn lint)
  deploy:
    name: Deploy
    needs: [ lint ]
    uses: ./.github/workflows/api-deploy.yml
    secrets: inherit
