name: CI

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/*.md'
      - 'LICENSE'
      - '**/.husky'
      - 'sanity-cms/**'
      - 'express-api/**'
      - 'rust-api/**'

concurrency: 
  group: ci
  cancel-in-progress: true

jobs:
  vitest:
    name: Run unit tests
    uses: ./.github/workflows/vitest.yml
  cypress:
    name: Run Cypress tests
    needs: [ vitest ]
    uses: ./.github/workflows/cypress.yml
  deploy:
    name: Deploy
    needs: [ cypress ]
    uses: ./.github/workflows/netlify-deploy.yml
    secrets: inherit
