name: Cypress

on:
  workflow_call:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install 2> >(grep -v warning 1>&2) && (cd ./svelte-app && yarn install 2> >(grep -v warning 1>&2))
      
      - name: Build testing environment
        env:
          SVELTE_ADAPTER_ENV: 'node'
        run: make build-test

      - name: Run tests
        run: make cypress
