name: Cypress

on:
  workflow_call:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: make install
      
      - name: Build testing env
        run: make build-test

      - name: Run cypress tests
        run: make cypress
