name: Build and Deploy

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/*.md"
      - "LICENSE"
      - "**/.husky"
      - "sanity-cms/**"

concurrency:
  group: main-pipeline-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node and pnpm
        uses: ./.github/actions/setup-node-pnpm
        with:
          working-directory: svelte-app
      - name: Install dependencies
        run: cd svelte-app && pnpm install --frozen-lockfile
      - name: Run lint check
        run: cd svelte-app && pnpm lint
  tests:
    name: Run Tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy:
    name: Deploy to Production
    needs: [quality-checks, tests]
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  # lint:
  #   name: Lint check
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Setup Node
  #       uses: actions/setup-node@v4
  #       with:
  #         node-version: 18.18.0
  #     - uses: pnpm/action-setup@v4
  #       name: Install pnpm
  #       id: pnpm-install
  #       with:
  #         run_install: false
  #     - name: Use node_modules cache
  #       uses: actions/cache@v4
  #       id: nm-cache
  #       with:
  #         path: "svelte-app/node_modules"
  #         key: ${{ runner.os }}-npm-${{ hashFiles('svelte-app/pnpm-lock.yaml') }}
  #         restore-keys: |
  #           ${{ runner.os }}-npm-
  #     - name: Install dependencies
  #       if: steps.nm-cache.outputs.cache-hit != 'true'
  #       run: make install-web
  #     - name: Run lint check
  #       run: (cd ./svelte-app && pnpm lint)
  # tests:
  #   name: Tests
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit
  # deploy:
  #   name: Deploy
  #   needs: [lint, tests]
  #   uses: ./.github/workflows/netlify-deploy.yml
  #   secrets: inherit
