name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make install

    - name: Run check
      run: make check
      
    - name: Run tests
      run: make test

    - name: Build app
      run: make prod
