name: Deploy (SvelteKit)

on:
  push:
    branches: ["main"]

concurrency:
  group: svelte-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SVELTE_ADAPTER_ENV: netlify
      VITE_APP_VERSION: ${{ github.sha }}
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: pnpm

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build --mode production

      - name: Deploy to Netlify
        run: pnpm netlify deploy --dir=./build --functions=./.netlify/functions-internal --prod --no-build
