name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

concurrency: 
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vitest:
    name: Vitest
    uses: ./.github/workflows/vitest.yml
  cypress:
    name: Cypress
    uses: ./.github/workflows/cypress.yml
