name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

concurrency: 
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  vitest:
    name: Vitest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16, 18 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Use node_modules cache
        uses: actions/cache@v3
        id: nm-cache
        with:
          path: 'svelte-app/node_modules'
          key: ${{ runner.os }}-nm-${{ matrix.node-version }}-${{ hashFiles('svelte-app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nm-${{ matrix.node-version }}-
      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
        if: steps.nm-cache.outputs.cache-hit != 'true'
        run: make install-web-ci
      - name: Run tests
        run: make vitest

  cypress:
    name: Cypress
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Use node_modules cache
        uses: actions/cache@v3
        id: nm-cache
        with:
          path: 'svelte-app/node_modules'
          key: ${{ runner.os }}-nm-16-${{ hashFiles('svelte-app/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-nm-16-
      - name: Install dependencies
        env:
          CYPRESS_INSTALL_BINARY: 0
        if: steps.nm-cache.outputs.cache-hit != 'true'
        run: make install-web-ci
      - name: Build testing environment
        env:
          SVELTE_ADAPTER_ENV: 'node'
        run: make test
      - name: Run tests
        run: make cypress
