name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_call:

concurrency: 
  group: test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8.6.0
          run_install: false
      - name: Use node_modules cache
        uses: actions/cache@v4
        id: nm-cache
        with:
          path: 'svelte-app/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('svelte-app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        if: steps.nm-cache.outputs.cache-hit != 'true'
        run: make install-web
      - name: Run tests
        run: make vitest

  integration:
    name: Integration tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18.17.0
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8.6.0
          run_install: false
      - name: Use node_modules cache
        uses: actions/cache@v4
        id: nm-cache
        with:
          path: 'svelte-app/node_modules'
          key: ${{ runner.os }}-npm-${{ hashFiles('svelte-app/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        if: steps.nm-cache.outputs.cache-hit != 'true'
        run: make install-web
      - name: Run tests
        run: make playwright
