name: Vitest

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  vitest-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      
    - name: Install dependencies
      run: make install

    - name: Run check
      run: make check
      
    - name: Run unit tests
      run: make vitest
